version: "3"

tasks:
  # 單元測試
  test:
    cmds:
      - go test ./... -cover

  # 啟動資料庫
  start:
    cmds:
      # 啟動 mariadb
      - docker build -t db-life -f docker/docker-mariadb .
      - docker rm -f -v db-life || true
      - docker volume rm db-life-volume || true
      - docker run -d --hostname db-life --name db-life --network dev -v db-life-volume:/data -e MARIADB_ROOT_PASSWORD=root -p 3306:3306 db-life
      # 清除懸空鏡像
      - docker image prune -f

  # 停止容器
  stop:
    cmds:
      - docker stop $(docker ps -q)

